server:
    port: 9090
spring:
    application:
        name: CarServiceRoman
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: gromenko23
        url: jdbc:mysql://localhost:3306/cardb
        username: root
    jpa:
        defer-datasource-initialization: false
        hibernate:
            ddl-auto: none
    liquibase:
        change-log: classpath:/db/changelog/db.changelog-master.yaml
        enabled: true
    sql:
        init:
            mode: always
